import React from 'react';
import { Link, Outlet, useLocation } from 'react-router-dom';
import { BookOpen, Calculator, FolderOpen, Moon, Settings, Sun, TrendingUp, UserCircle, Zap } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useTheme } from '@/lib/ThemeContext';

const TABS=[
 {key:'estimates',path:'/',label:'Estimates',icon:FolderOpen},
 {key:'new',path:'/estimates/new',label:'New Estimate',icon:Calculator},
 {key:'labor',path:'/labor',label:'Labor',icon:BookOpen},
 {key:'production',path:'/production',label:'Production',icon:TrendingUp},
];
export default function AppLayout(){const location=useLocation();const{theme,toggleTheme}=useTheme();const active=t=>t.path==='/'?location.pathname==='/':location.pathname.startsWith(t.path);return <div className="min-h-dvh bg-background flex flex-col"><header className="sticky top-0 z-50 border-b border-border/60 bg-background/80 backdrop-blur-xl shadow-sm" style={{paddingTop:'env(safe-area-inset-top)'}}><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between h-14"><Link to="/" className="flex items-center gap-2.5"><div className="grid w-8 h-8 place-items-center rounded-xl bg-amber-400 text-slate-950"><Zap className="w-5 h-5"/></div><div><h1 className="text-sm font-bold leading-none">Estim8r</h1><p className="text-[9px] font-semibold text-muted-foreground tracking-widest uppercase">Electrical Estimating</p></div></Link><div className="flex items-center gap-1"><nav className="hidden sm:flex items-center gap-1">{TABS.map(t=>{const I=t.icon;return <Link key={t.key} to={t.path}><div className={cn('flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all',active(t)?'bg-amber-400 text-slate-950 shadow-md':'text-muted-foreground hover:text-foreground hover:bg-muted')}><I className="w-3.5 h-3.5"/>{t.label}</div></Link>})}</nav><button onClick={toggleTheme} className="ml-1 w-8 h-8 rounded-full bg-muted flex items-center justify-center" aria-label="Toggle dark mode">{theme==='dark'?<Sun className="w-4 h-4"/>:<Moon className="w-4 h-4"/>}</button><Link to="/settings" className="ml-1 w-8 h-8 rounded-full bg-muted flex items-center justify-center"><Settings className="w-4 h-4"/></Link><Link to="/profile" className="ml-1 w-8 h-8 rounded-full bg-muted flex items-center justify-center"><UserCircle className="w-5 h-5"/></Link></div></div></div></header><main className="flex-1 max-w-7xl mx-auto w-full px-3 sm:px-6 lg:px-8 py-4 pb-24 sm:pb-8"><Outlet/></main><nav className="sm:hidden fixed bottom-0 left-0 right-0 z-50 bg-background/90 backdrop-blur-xl border-t border-border/60" style={{paddingBottom:'env(safe-area-inset-bottom)'}}><div className="flex items-center justify-around py-1.5 px-2">{TABS.map(t=>{const I=t.icon;const a=active(t);return <Link key={t.key} to={t.path} className="flex-1"><div className={cn('flex flex-col items-center gap-1 py-1.5',a?'text-amber-500':'text-muted-foreground')}><I className="w-5 h-5"/><span className="text-[10px] font-semibold">{t.label}</span></div></Link>})}</div></nav></div>}
