import React,{useMemo,useState} from 'react';
import { calculateEstimatedHours } from '@/domain/labor/laborEngine';

const FACTORS=[['Height > 15 ft',1.10],['Occupied building',1.08],['Congested ceiling',1.15],['Long material handling',1.05],['Night shift',1.07],['Prefab',0.90],['Repetitive installation',0.95]];
export default function EstimateBuilder(){
 const [qty,setQty]=useState(1850),[per,setPer]=useState(100),[base,setBase]=useState(5),[override,setOverride]=useState(''),[active,setActive]=useState([]);
 const factors=active.map(i=>({id:String(i),code:`factor_${i}`,label:FACTORS[i][0],multiplier:FACTORS[i][1],category:'custom'}));
 const result=useMemo(()=>calculateEstimatedHours({quantity:Number(qty)||0,quantityPerLaborUnit:Number(per)||1,selection:{laborItemId:'preview',selectedSource:'custom',condition:'normal',baseMhPerUnit:Number(base)||0,factors,estimatorOverrideMhPerUnit:override===''?null:Number(override),overrideReason:override?'Estimator manual override':''}}),[qty,per,base,override,active]);
 function toggle(i){setActive(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i])}
 return <div className="p-8"><p className="text-sm font-semibold uppercase tracking-widest text-amber-400">Estimate Builder</p><h1 className="mb-2 text-3xl font-black">Labor Calculation Workspace</h1><p className="mb-7 text-slate-400">This first production slice exposes every labor assumption instead of hiding adjustments inside the estimate.</p><div className="grid grid-cols-3 gap-6"><section className="col-span-2 rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="mb-5 text-lg font-bold">Estimate Line</h2><div className="grid grid-cols-3 gap-4"><Field label="Quantity" value={qty} set={setQty}/><Field label="Quantity / Labor Unit" value={per} set={setPer}/><Field label="Base MH / Unit" value={base} set={setBase}/></div><h3 className="mb-3 mt-7 font-semibold">Productivity Factors</h3><div className="grid grid-cols-2 gap-2">{FACTORS.map((f,i)=><button key={f[0]} onClick={()=>toggle(i)} className={`flex justify-between rounded-lg border p-3 text-left text-sm ${active.includes(i)?'border-amber-400 bg-amber-400/10':'border-slate-700'}`}><span>{f[0]}</span><span>×{f[1].toFixed(2)}</span></button>)}</div><div className="mt-6"><label className="mb-2 block text-sm text-slate-400">Estimator Override MH / Unit</label><input value={override} onChange={e=>setOverride(e.target.value)} type="number" step="0.01" placeholder="Optional — estimator remains in control" className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-3"/></div></section><aside className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="mb-5 text-lg font-bold">Labor Result</h2><Metric label="Base MH / Unit" value={result.baseMhPerUnit.toFixed(2)}/><Metric label="Factor Multiplier" value={`×${result.factorMultiplier.toFixed(3)}`}/><Metric label="Calculated MH / Unit" value={result.calculatedMhPerUnit.toFixed(2)}/><Metric label="Effective MH / Unit" value={result.effectiveMhPerUnit.toFixed(2)}/><div className="mt-5 border-t border-slate-700 pt-5"><div className="text-sm text-slate-400">Estimated Labor</div><div className="mt-1 text-4xl font-black text-amber-400">{result.estimatedHours.toFixed(2)} <span className="text-lg">hrs</span></div></div>{result.isOverride&&<div className="mt-4 rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-200">Manual estimator override applied.</div>}</aside></div></div>
}
function Field({label,value,set}){return <label><span className="mb-2 block text-sm text-slate-400">{label}</span><input value={value} onChange={e=>set(e.target.value)} type="number" step="0.01" className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-3"/></label>}
function Metric({label,value}){return <div className="flex justify-between border-b border-slate-800 py-3 text-sm"><span className="text-slate-400">{label}</span><strong>{value}</strong></div>}
