import React,{useMemo,useState} from 'react';
import { Plus, Trash2 } from 'lucide-react';

const ITEM_TYPES=['Material','Labor','Equipment','Subcontract','Allowance','Fixture','Device','Conduit','Wire','Gear','Other'];
const UNITS=['EA','LF','FT','100 LF','1000 LF','HR','DAY','LOT'];
const blankLine=()=>({id:crypto.randomUUID(),itemType:'Material',category:'',description:'',quantity:1,unit:'EA',materialUnitCost:0,laborMhPerUnit:0,laborRate:0,notes:''});

export default function EstimateBuilder(){
 const [header,setHeader]=useState({projectName:'',projectAddress:'',estimateNumber:'',customerCompany:'',customerName:'',customerPhone:'',customerEmail:'',estimatorName:'',bidDue:'',scopeNotes:''});
 const [lines,setLines]=useState([blankLine()]),[overhead,setOverhead]=useState(10),[profit,setProfit]=useState(10);
 const totals=useMemo(()=>lines.reduce((a,l)=>{const q=Number(l.quantity)||0;a.material+=q*(Number(l.materialUnitCost)||0);a.hours+=q*(Number(l.laborMhPerUnit)||0);a.labor+=q*(Number(l.laborMhPerUnit)||0)*(Number(l.laborRate)||0);return a},{material:0,hours:0,labor:0}),[lines]);
 const direct=totals.material+totals.labor,oh=direct*((Number(overhead)||0)/100),sub=direct+oh,prof=sub*((Number(profit)||0)/100),grand=sub+prof;
 const h=(k,v)=>setHeader(x=>({...x,[k]:v}));
 const line=(id,k,v)=>setLines(x=>x.map(r=>r.id===id?{...r,[k]:v}:r));
 return <div className="space-y-5 py-4">
  <div><p className="text-xs font-bold uppercase tracking-widest text-blue-600 dark:text-orange-500">Estimate Builder</p><h1 className="text-3xl font-black">Electrical Estimate</h1><p className="text-sm text-muted-foreground">Project, customer, scope, material and labor in one estimate.</p></div>
  <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="mb-4 text-lg font-bold">Project & Customer</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
   <Field label="Project name" value={header.projectName} set={v=>h('projectName',v)}/><Field label="Estimate #" value={header.estimateNumber} set={v=>h('estimateNumber',v)}/><Field label="Customer / company" value={header.customerCompany} set={v=>h('customerCompany',v)}/><Field label="Contact name" value={header.customerName} set={v=>h('customerName',v)}/>
   <Field label="Phone" type="tel" value={header.customerPhone} set={v=>h('customerPhone',v)}/><Field label="Email" type="email" value={header.customerEmail} set={v=>h('customerEmail',v)}/><Field label="Estimator" value={header.estimatorName} set={v=>h('estimatorName',v)}/><Field label="Bid due" type="datetime-local" value={header.bidDue} set={v=>h('bidDue',v)}/>
  </div><div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="Project address" value={header.projectAddress} set={v=>h('projectAddress',v)}/><Field label="Scope / bid notes" value={header.scopeNotes} set={v=>h('scopeNotes',v)}/></div></section>
  <section className="rounded-2xl border border-border bg-card shadow-sm"><div className="flex items-center justify-between border-b border-border p-4"><div><h2 className="text-lg font-bold">Estimate Lines</h2><p className="text-xs text-muted-foreground">Add material, labor, equipment, fixtures, devices, conduit, wire, gear and custom items.</p></div><button onClick={()=>setLines(x=>[...x,blankLine()])} className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white dark:bg-orange-500"><Plus className="h-4 w-4"/>Add line</button></div>
   <div className="overflow-x-auto"><table className="min-w-[1250px] w-full text-sm"><thead className="bg-muted text-left text-xs uppercase text-muted-foreground"><tr><th className="p-3">Type</th><th>Category</th><th>Item / description</th><th>Qty</th><th>Unit</th><th>Material $/unit</th><th>MH/unit</th><th>Labor $/hr</th><th>Material</th><th>Labor</th><th>Notes</th><th></th></tr></thead><tbody>
    {lines.map(r=>{const q=Number(r.quantity)||0;const mat=q*(Number(r.materialUnitCost)||0);const lab=q*(Number(r.laborMhPerUnit)||0)*(Number(r.laborRate)||0);return <tr key={r.id} className="border-t border-border"><td className="p-2"><Sel value={r.itemType} vals={ITEM_TYPES} set={v=>line(r.id,'itemType',v)}/></td><td className="p-2"><Cell value={r.category} set={v=>line(r.id,'category',v)}/></td><td className="p-2"><Cell value={r.description} set={v=>line(r.id,'description',v)} placeholder="Item description"/></td><td className="p-2"><Cell type="number" value={r.quantity} set={v=>line(r.id,'quantity',v)}/></td><td className="p-2"><Sel value={r.unit} vals={UNITS} set={v=>line(r.id,'unit',v)}/></td><td className="p-2"><Cell type="number" value={r.materialUnitCost} set={v=>line(r.id,'materialUnitCost',v)}/></td><td className="p-2"><Cell type="number" value={r.laborMhPerUnit} set={v=>line(r.id,'laborMhPerUnit',v)}/></td><td className="p-2"><Cell type="number" value={r.laborRate} set={v=>line(r.id,'laborRate',v)}/></td><td className="p-3 font-semibold">{'$'}{mat.toFixed(2)}</td><td className="p-3 font-semibold">{'$'}{lab.toFixed(2)}</td><td className="p-2"><Cell value={r.notes} set={v=>line(r.id,'notes',v)}/></td><td className="p-2"><button onClick={()=>setLines(x=>x.length===1?x:x.filter(z=>z.id!==r.id))} className="p-2 text-destructive"><Trash2 className="h-4 w-4"/></button></td></tr>})}
   </tbody></table></div>
  </section>
  <section className="grid gap-4 lg:grid-cols-[1fr_340px]"><div className="rounded-2xl border border-border bg-card p-4"><h2 className="font-bold">Estimate controls</h2><div className="mt-3 grid grid-cols-2 gap-3"><Field label="Overhead %" type="number" value={overhead} set={setOverhead}/><Field label="Profit %" type="number" value={profit} set={setProfit}/></div></div><div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><Sum label="Material" value={totals.material}/><Sum label={'Labor ('+totals.hours.toFixed(2)+' hrs)'} value={totals.labor}/><Sum label={'Overhead ('+(Number(overhead)||0)+'%)'} value={oh}/><Sum label={'Profit ('+(Number(profit)||0)+'%)'} value={prof}/><div className="mt-3 flex justify-between border-t border-border pt-4 text-xl font-black"><span>Estimate Total</span><span className="text-blue-600 dark:text-orange-500">{'$'}{grand.toFixed(2)}</span></div></div></section>
 </div>
}
function Field({label,value,set,type='text'}){return <label><span className="mb-1 block text-xs font-bold text-muted-foreground">{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)} className="w-full rounded-lg border border-input bg-background px-3 py-2.5"/></label>}
function Cell({value,set,type='text',placeholder=''}){return <input type={type} step={type==='number'?'0.01':undefined} value={value} placeholder={placeholder} onChange={e=>set(e.target.value)} className="w-full min-w-24 rounded-md border border-input bg-background px-2 py-2"/>}
function Sel({value,vals,set}){return <select value={value} onChange={e=>set(e.target.value)} className="min-w-28 rounded-md border border-input bg-background px-2 py-2">{vals.map(v=><option key={v}>{v}</option>)}</select>}
function Sum({label,value}){return <div className="flex justify-between border-b border-border py-2 text-sm"><span className="text-muted-foreground">{label}</span><strong>{'$'}{value.toFixed(2)}</strong></div>}
