import React, { useEffect, useState } from 'react';
import { Search, ShieldAlert, ShieldCheck } from 'lucide-react';
import { listLaborLibrary } from '@/api/laborRepository';

export default function LaborLibrary(){
 const [rows,setRows]=useState([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const timer=setTimeout(async()=>{setLoading(true);try{setRows(await listLaborLibrary({search}));setError('')}catch(e){setError(e.message)}finally{setLoading(false)}},250);return()=>clearTimeout(timer)},[search]);
 return <div className="p-8"><div className="mb-6"><p className="text-sm font-semibold uppercase tracking-widest text-amber-400">Labor Intelligence</p><h1 className="text-3xl font-black">Master Labor Library</h1><p className="mt-2 text-slate-400">Every labor value carries its source and verification status.{!loading && !error ? ` ${rows.length} item${rows.length === 1 ? "" : "s"} shown.` : ""}</p></div><div className="relative mb-6 max-w-2xl"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search EMT, transformer, fiber, access control…" className="w-full rounded-xl border border-slate-700 bg-slate-900 py-3 pl-10 pr-4"/></div>{error&&<div className="mb-5 rounded-lg bg-red-500/10 p-3 text-red-200">{error}</div>}<div className="overflow-hidden rounded-2xl border border-slate-800"><table className="w-full text-left text-sm"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-4">Item</th><th>Category</th><th>Size</th><th>Unit</th><th>Labor Sources</th></tr></thead><tbody>{loading?<tr><td colSpan="5" className="p-8 text-center text-slate-500">Loading labor library…</td></tr>:rows.map(r=><tr key={r.id} className="border-t border-slate-800"><td className="p-4"><div className="font-semibold">{r.item_name}</div><div className="text-xs text-slate-500">{r.description}</div></td><td>{r.category}<div className="text-xs text-slate-500">{r.subcategory}</div></td><td>{r.size||'—'}</td><td>{r.unit}</td><td className="pr-4">{(r.labor_units||[]).length===0?<span className="text-slate-500">No sourced labor yet</span>:(r.labor_units||[]).map(u=><div key={u.id} className="my-1 flex items-center gap-2">{u.verification_status==='verified'&&u.production_allowed?<ShieldCheck className="h-4 w-4 text-emerald-400"/>:<ShieldAlert className="h-4 w-4 text-amber-400"/>}<span>{u.source_name}: {u.normal_mh ?? '—'} MH</span><span className="text-xs text-slate-500">{u.verification_status}</span></div>)}</td></tr>)}</tbody></table></div></div>
}
